FROM openjdk:17-jdk
WORKDIR /app
COPY target/FlightSimulation-0.0.1-SNAPSHOT.jar /app/FlightSimulation-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "FlightSimulation-0.0.1-SNAPSHOT.jar"]